# Generated by Django 5.1.6 on 2025-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="point",
            name="description",
        ),
        migrations.AddField(
            model_name="point",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="Địa chỉ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="point",
            name="routes",
            field=models.CharField(
                default=" ", max_length=255, verbose_name="Các tuyến đi qua"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="point",
            name="latitude",
            field=models.FloatField(verbose_name="Vĩ độ"),
        ),
        migrations.AlterField(
            model_name="point",
            name="longitude",
            field=models.FloatField(verbose_name="Kinh độ"),
        ),
    ]
