# Generated by Django 5.1.7 on 2025-04-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
