# Generated by Django 5.1.7 on 2025-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='points',
        ),
        migrations.AddField(
            model_name='post',
            name='points_inbound',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='points_outbound',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
